services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes: 
      - /var/lib/postgresql/data
  
  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITIDB_ROOT_USERNAME=root
      - MONGO_INITIDB_ROOT_PASSWORD=mongopw
      ## não está setando o password!
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672